// ─────────────────────────────────────────────────────────────────────────────
// parser-fs — the collection scanner: pages that list themselves.
//
// WHY THIS EXISTS. A page is a co-located folder (page.tsx + _data). Whoever
// draws a menu or an index needs the list of those folders, but Turbopack
// (webpack is prohibited here) needs STATICALLY resolvable imports, so the list
// cannot be discovered at runtime. This script discovers them at BUILD time and
// writes a plain `_list.generated.ts` next to them: static imports plus a PAGES
// array. The runtime stays fully static and works without JavaScript, and
// nobody maintains a list by hand.
//
// 🔒 IT WALKS A TREE, IT DOES NOT READ A LIST OF COLLECTIONS. An earlier shape
// took one entry per collection — and that simply moved the hand-written list
// one level up: adding a group meant editing this file. A list nobody has to
// edit is the entire point, so the rule is positional instead:
//
//     write `_list.generated.ts` into EVERY folder whose direct children
//     include folders that carry `_data/index.ts`
//
// Depth therefore stops being a parameter. One level (a blog) and two levels
// (a layer of groups and sections) are the same case, and a third would need no
// change here.
//
// 🔒 THE GENERATED FILE IS COMMITTED, NOT IGNORED — the owner's decision
// 2026-08-21, and the reasoning is written out in `.gitignore` where the old
// rule used to stand: the list is part of the architecture the owner must be
// able to see on his own machine without building first, and it must reach the
// server the ordinary way, through GitHub, together with the page it names.
//
// 🛑 IT IS STILL NOT A SOURCE FILE. Edit a page's folder, never this output: the
// next build overwrites it without asking.
//
// Node ESM, zero deps — runs with bare `node lib/parser-fs.mjs` on any Node.
// ─────────────────────────────────────────────────────────────────────────────

import { readdirSync, existsSync, writeFileSync, statSync, readFileSync, unlinkSync } from 'node:fs'
import { join } from 'node:path'

// Roots to walk. A root is not a collection — it is where walking starts; every
// folder below it that has page-children gets its own list.
//
// `type`/`typeModule` name the type each page's `_data/index.ts` exports as
// `data`. The module is written with `@/` on purpose: a relative path would
// depend on the depth of the folder the list lands in, and lists land at any
// depth.
const ROOTS = [
  {
    dir: 'app/[lang]/(architectLayer)/architect',
    type: 'WorkspacePageData',
    typeModule: '@/lib/collection/types',
  },
]

/** Folders Next treats as special, plus dotfiles: never pages. */
function isPageFolder(parent, name) {
  if (name.startsWith('_') || name.startsWith('[') || name.startsWith('.') || name.startsWith('(')) return false
  return statSync(join(parent, name)).isDirectory()
}

/** A page folder = a child folder carrying `_data/index.ts`. */
function pageChildren(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((name) => isPageFolder(dir, name))
    .filter((name) => existsSync(join(dir, name, '_data', 'index.ts')))
    .sort() // deterministic import order; the runtime sorts by meta.order
}

/** Every child folder worth descending into — a page folder or not. */
function childFolders(dir) {
  if (!existsSync(dir)) return []
  return readdirSync(dir).filter((name) => isPageFolder(dir, name))
}

/**
 * Renders the list for one folder.
 *
 * 🔒 IT EMITS TWO THINGS, AND THE SECOND IS WHAT MAKES DEPTH FREE. `PAGES` is
 * this folder's own children. `TREE` pairs each child with ITS children, taken
 * from the child's own generated list — so a menu of groups-with-sections is
 * built from one import instead of one import per group, and adding a group
 * changes no source file at all.
 *
 * A child with no children of its own gets an empty array, which is a legal
 * state: a group of a single page has nothing to unfold.
 */
function render({ dir, slugs, type, typeModule }) {
  const dataImports = slugs.map((slug, i) => `import { data as p${i} } from './${slug}/_data'`)
  const listImports = []
  const branches = []

  slugs.forEach((slug, i) => {
    const childHasList = pageChildren(join(dir, slug)).length > 0
    if (childHasList) {
      listImports.push(`import { PAGES as c${i} } from './${slug}/_list.generated'`)
      branches.push(`  { page: p${i}, children: c${i} },`)
    } else {
      branches.push(`  { page: p${i}, children: [] },`)
    }
  })

  const arr = slugs.map((_, i) => `p${i}`).join(', ')
  return `// AUTO-GENERATED by lib/parser-fs.mjs — DO NOT EDIT.
// Rewritten on every build and every dev start (npm prebuild / predev).
// Lists every child folder of this one that carries _data/index.ts.
import type { ${type}, CollectionBranch } from '${typeModule}'
${[...dataImports, ...listImports].join('\n')}

export const PAGES: ${type}[] = [${arr}]

/** Each child together with its own children — see the law in the generator. */
export const TREE: CollectionBranch[] = [
${branches.join('\n')}
]
`
}

/**
 * Walks one folder, writes its list when it has page children, then descends.
 *
 * Returns how many lists were written and how many pages they name.
 */
function walk(dir, root, acc) {
  // 🛑 СНАЧАЛА ДЕТИ, ПОТОМ РОДИТЕЛЬ. Список родителя ссылается на списки детей;
  // родись он первым, он ссылался бы на файлы, которых ещё нет, и первая сборка
  // на чистом клоне падала бы на импорте.
  for (const name of childFolders(dir)) walk(join(dir, name), root, acc)

  const slugs = pageChildren(dir)

  const out = join(dir, '_list.generated.ts')

  // 🛑 A LIST WITHOUT PAGES IS DELETED, NOT LEFT ALONE — and this was found by
  // testing the layer's README, not by reasoning (254-7).
  //
  // ✗ WHAT HAPPENED. The README promises: "delete every page, run the generator,
  // and the project compiles again". It did not. With no page children the
  // generator simply wrote nothing, so the PREVIOUS list survived — naming five
  // folders that no longer existed. The menu imports it, so the build died on an
  // import, and the документ that was supposed to rescue the situation made it
  // worse by sounding certain.
  //
  // 🔒 THE CLASS IS WIDER THAN THIS FILE: a generator that only ever WRITES leaves
  // its own past behind. Deleting is half of generating.
  // 🔒 THE ROOT'S LIST ALWAYS EXISTS, EVEN EMPTY — and this is the second half of
  // the same lesson. The layer's skeleton imports it (the menu does), so deleting
  // it would break the very files that are supposed to SURVIVE losing all pages.
  // An empty list is a layer with no pages; a missing one is a layer that will not
  // compile. Nested folders have no such obligation: nobody imports them but their
  // own parent, which is regenerated in the same run.
  const isRoot = dir === root.dir

  if (slugs.length === 0 && !isRoot) {
    if (existsSync(out)) {
      unlinkSync(out)
      acc.removed.push(out)
    }
    return
  }

  {
    const body = render({ dir, slugs, type: root.type, typeModule: root.typeModule })
    // Written only when it actually differs: an untouched mtime keeps dev
    // servers from restarting themselves on every prebuild.
    const before = existsSync(out) ? readFileSync(out, 'utf8') : null
    if (before !== body) writeFileSync(out, body, 'utf8')
    acc.lists += 1
    acc.pages += slugs.length
    acc.written.push(`${out} (${slugs.length})`)
  }
}

const acc = { lists: 0, pages: 0, written: [], removed: [] }
// A root that is not here (a site without the architect pages) has nothing to list.
for (const root of ROOTS) if (existsSync(root.dir)) walk(root.dir, root, acc)

for (const line of acc.written) console.log(`parser-fs: ${line}`)
for (const line of acc.removed) console.log(`parser-fs: УДАЛЁН устаревший список ${line}`)
console.log(`===PARSER_FS_OK=== lists: ${acc.lists}, pages: ${acc.pages}, удалено устаревших: ${acc.removed.length}`)
